// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSettingsSearchEntry } from "./PluginSettingsSearchEntry";

export type PluginSettingsSection = { plugin_name: string, section_id: string, section_key: string, label: string, description: string | null, keywords: string | null, group: string, view_id: string, settings: Array<PluginSettingsSearchEntry>, };
