// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a plugin-owned docked split view.
 */
export type PluginViewInfo = { view_id: string, plugin_name: string, pane_id: number, tab_id: number, title: string, icon: string | null, last_widgets_json: string, };
