// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginSettingsSearchEntry = { id: string, label: string, description: string | null, keywords: string | null, };
