// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplyChangesResponse = { "kind": "applied", version: number, } | { "kind": "resyncRequired", expectedVersion: number, receivedBaseVersion: number, };
