// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceFingerprint } from "./SourceFingerprint";

export type AttentionReason = { "kind": "destinationConflict", resumeAvailable: boolean, } | { "kind": "sourceChanged", expected: SourceFingerprint, actual: SourceFingerprint, } | { "kind": "sourceCannotResume" } | { "kind": "sourceMissing" } | { "kind": "missingPartial" } | { "kind": "commitRecovery", message: string, } | { "kind": "cleanup", message: string, };
