// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchInfo } from "./BatchInfo";

export type BatchAggregate = { info: BatchInfo, filesDone: number, bytesDone: number, speedBytesPerSecond: number | null, etaSeconds: number | null, };
