// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchExpansion } from "./BatchExpansion";
import type { TransferDirection } from "./TransferDirection";

export type BatchInfo = { id: string, name: string, direction: TransferDirection, expansion: BatchExpansion, discoveredFiles: number, discoveredBytes: number, 
/**
 * Symlinks (and other skipped entries) recorded during expansion.
 */
skipped: Array<string>, createdAtMs: number, };
