// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchExpansion = { "kind": "running" } | { "kind": "complete" } | { "kind": "interrupted", reason: string, };
