// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorRange } from "./EditorRange";

export type CompletionTextEdit = { "kind": "textEdit", range: EditorRange, newText: string, } | { "kind": "insertReplaceEdit", insert: EditorRange, replace: EditorRange, newText: string, };
