// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionItem } from "./CompletionItem";

export type CompletionResponse = { documentId: string, sourceVersion: number, isIncomplete: boolean, items: Array<CompletionItem>, };
