// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionTextEdit } from "./CompletionTextEdit";
import type { CompletionUnsupportedEffect } from "./CompletionUnsupportedEffect";
import type { EditorTextEdit } from "./EditorTextEdit";
import type { HoverBlock } from "./HoverBlock";

export type CompletionItem = { id: string, label: string, detail: string | null, 
/**
 * A stable frontend category such as `function`, `variable`, or `file`;
 * never the numeric LSP `CompletionItemKind` value.
 */
kind: string | null, documentation: Array<HoverBlock>, sortText: string | null, filterText: string | null, insertText: string | null, isSnippet: boolean, textEdit: CompletionTextEdit | null, additionalTextEdits: Array<EditorTextEdit>, commitCharacters: Array<string>, deprecated: boolean, unsupportedEffects: Array<CompletionUnsupportedEffect>, };
