// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A detached session as the frontend sees it.
 */
export type ConnectedSession = { sessionKey: string, host: string, user: string, port: number, paneId: number, };
