// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { DiagnosticCounts } from "./DiagnosticCounts";

export type DiagnosticSnapshot = { revision: bigint, items: Array<Diagnostic>, counts: DiagnosticCounts, };
