// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSnapshot } from "./DiagnosticSnapshot";

export type DiagnosticUpdate = { revision: bigint, sessionId: string | null, documentId: string | null, uri: string | null, snapshot: DiagnosticSnapshot, };
