// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticRelatedInformation } from "./DiagnosticRelatedInformation";
import type { DiagnosticSeverity } from "./DiagnosticSeverity";
import type { EditorRange } from "./EditorRange";

export type Diagnostic = { id: string, uri: string, range: EditorRange, severity: DiagnosticSeverity, code: string | null, source: string | null, message: string, relatedInformation: Array<DiagnosticRelatedInformation>, };
