// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorLocation } from "./EditorLocation";

export type DiagnosticRelatedInformation = { location: EditorLocation, message: string, };
