// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorRange } from "./EditorRange";

export type EditorTextEdit = { range: EditorRange, newText: string, };
