// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorPosition } from "./EditorPosition";

export type EditorRange = { start: EditorPosition, end: EditorPosition, };
