// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a `share_export` call with this selection would produce, computed
 * by actually running the planner — never a frontend-side guess. Returned
 * to the frontend so it can show the user exactly what will be written
 * (auto-pulled hosts, which keys would be embedded, every warning) and let
 * them cancel before anything is encoded or saved to disk, per the design
 * spec's export step 5 ("Preview... The user confirms or cancels") and
 * 2026-08-16 review finding I3: today's flow ran the save dialog and wrote
 * the file *before* showing any of this, with no way to back out.
 *
 * Deliberately carries no key material — only each embedded key's
 * `comment` (a filename, e.g. `id_ed25519`; see
 * `export_planner::embed_key_for_account`) — so the wire payload back to
 * the frontend never contains secrets, and the full plan (which does hold
 * key bytes, `Zeroizing` end-to-end) is dropped at the end of this
 * function rather than cached in any backend state.
 */
export type ExportPreview = { servers: number, tunnels: number, credentials: number, keys: Array<string>, warnings: Array<string>, auto_pulled: Array<string>, };
