// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local account and machine name for titles ("dustin@mbp: ...").
 *
 * Neither changes while the app runs, so the frontend fetches this once at
 * startup rather than including it in the per-tick pane poll. The hostname is
 * shortened at the first dot: "mbp.local" reads as "mbp", matching what a
 * shell prompt shows.
 */
export type HostIdentity = { user: string, host: string, 
/**
 * Used to collapse a leading home directory to "~" in titles.
 */
home: string, };
