// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorRange } from "./EditorRange";
import type { HoverBlock } from "./HoverBlock";

export type HoverResponse = { documentId: string, sourceVersion: number, range: EditorRange | null, blocks: Array<HoverBlock>, };
