// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HoverBlock = { 
/**
 * True only after the backend has accepted and normalized Markdown from
 * the server. The frontend still sanitizes it before inserting DOM.
 */
markdown: boolean, value: string, };
