// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportPreviewRow = { kind: string, id: string, label: string, detail: string, status: string, default_action: string, };
