// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportFileInfo = { path: string, 
/**
 * `"bundle"` for an encrypted `.termlabshare` file, `"legacy_json"` for
 * anything else — decided by `detect_import_kind`'s magic-byte check,
 * never by the file's extension.
 */
kind: string, };
