// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportPreviewRow } from "./ImportPreviewRow";

/**
 * What `share_import_apply` would do with every decision left at its
 * default — computed by actually running the planner, never guessed on the
 * frontend. Mutates nothing: no file is written, no config is touched, no
 * vault is opened beyond a read of its lock state.
 */
export type ImportPreview = { rows: Array<ImportPreviewRow>, includes_credentials: boolean, vault_state: string, };
