// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspTextChange } from "./LspTextChange";

export type LspChangeBatch = { documentId: string, baseVersion: number, nextVersion: number, changes: Array<LspTextChange>, };
