// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspSessionState = "disabled" | "choosingProject" | "untrusted" | "starting" | "indexing" | "ready" | "failed" | "unavailable";
