// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspTextChange = { fromUtf16: number, toUtf16: number, insertedText: string, };
