// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stable reason why a curated language adapter cannot be started. The
 * catalog keeps the detailed filesystem validation error internal, while the
 * manager later exposes this normalized status to the frontend.
 */
export type LspUnavailableReason = { "kind": "notBundledYet", adapterId: string, } | { "kind": "missingResource", adapterId: string, relativePath: string, } | { "kind": "corruptResource", adapterId: string, relativePath: string, } | { "kind": "unsupportedPlatform", expected: string, actual: string, } | { "kind": "unsupportedArchitecture", expected: string, actual: string, };
