// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspStatus } from "./LspStatus";
import type { ProjectCandidate } from "./ProjectCandidate";

export type OpenDocumentResponse = { documentId: string, version: number, projectCandidates: Array<ProjectCandidate>, status: LspStatus, };
