// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PalettePreview = { bg: string, fg: string, ansi: [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string], };
