// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Working directory plus foreground program for a local pane, in one call.
 *
 * The title poll runs on a timer for the active tab, so this deliberately
 * returns both halves together rather than making the frontend issue two IPC
 * round trips per tick. `program` is None when the shell itself is in the
 * foreground — see `PtyBackend::foreground_program`.
 */
export type PaneProcessInfo = { cwd: string | null, program: string | null, };
