// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectCandidate = { rootUri: string, canonicalPath: string, displayName: string, marker: string, reason: string, confidence: number, isFallback: boolean, };
