// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchAggregate } from "./BatchAggregate";
import type { QueueSettings } from "./QueueSettings";
import type { TransferJob } from "./TransferJob";

export type QueueEventPayload = { revision: number, upserts: Array<TransferJob>, removedIds: Array<string>, queuePaused: boolean, settings: QueueSettings, 
/**
 * Full batch-aggregate projection, derived fresh from the committed
 * document on every emission. There are no per-batch deltas: batch
 * counts are small enough that resending the whole list each time is
 * simpler than tracking incremental batch changes.
 */
batches: Array<BatchAggregate>, };
