// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueSettings } from "./QueueSettings";
import type { TransferJob } from "./TransferJob";

export type QueueEventPayload = { revision: number, upserts: Array<TransferJob>, removedIds: Array<string>, queuePaused: boolean, settings: QueueSettings, };
