// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueueSettings = { globalLimit: number, perHostLimit: number, 
/**
 * Chunk requests kept in flight per transfer attempt (1 = sequential).
 */
pipelineDepth: number, 
/**
 * Requested bytes per chunk; clamped to the server limit at attempt time.
 */
pipelineChunkBytes: number, };
