// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransferQueueSummary } from "./TransferQueueSummary";

export type QueueSummaryPayload = { revision: number, summary: TransferQueueSummary, };
