// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorLocation } from "./EditorLocation";

/**
 * `textDocument/references`. Deliberately its own type rather than a reuse of
 * `DefinitionResponse`: the payloads are shaped alike, but they answer
 * different questions, and the Tauri contract names the type the frontend
 * gets back.
 */
export type ReferencesResponse = { documentId: string, sourceVersion: number, locations: Array<EditorLocation>, };
