// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentId } from "./DocumentId";
import type { ReservationId } from "./ReservationId";

export type ReserveResult = { "kind": "reserved", reservationId: ReservationId, canonicalPath: string, } | { "kind": "focusPending", windowLabel: string, } | { "kind": "focusOwner", documentId: DocumentId, windowLabel: string, paneId: string, };
