// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspStatus } from "./LspStatus";

export type ResyncDocumentResponse = { documentId: string, version: number, status: LspStatus, };
