// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Layout state sent to the frontend on load.
 */
export type SavedLayout = { window_width: number, window_height: number, ssh_panel_width: number, ssh_panel_visible: boolean, files_panel_width: number, files_panel_visible: boolean, bottom_panel_visible: boolean, bottom_panel_height: number, zen_mode: boolean, tool_window_zones: { [key in string]: string }, active_tool_windows: { [key in string]: string }, 
/**
 * The read-back twin of [`WindowLayout::tool_window_view_modes`], mirroring
 * `tool_window_zones` above exactly. Without it the frontend could write a
 * view mode but never learn it again, so a popped-out tool window would
 * silently come back docked on the next launch.
 */
tool_window_view_modes: { [key in string]: string }, left_split_ratio: number, right_split_ratio: number, bottom_split_ratio: number, };
