// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a detached connect could not complete.
 *
 * Internally tagged so the frontend discriminates on `err.kind` and reads the
 * variant's own fields off the same object. `AuthFailed`/`Unreachable`/`Other`
 * carry the underlying `RemoteError`'s message, which never contains a
 * credential: `termlab_remote` builds its auth errors from russh's error
 * Display, and no call site in this module formats a password into anything.
 */
export type SftpConnectError = { "kind": "vaultLocked" } | { "kind": "needsPassword", hasVaultAccount: boolean, } | { "kind": "authFailed", message: string, } | { "kind": "unreachable", message: string, } | { "kind": "other", message: string, };
