// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareExportSummary = { path: string, servers: number, tunnels: number, credentials: number, warnings: Array<string>, 
/**
 * Servers pulled into the bundle beyond what the user ticked, because a
 * selected tunnel depends on them (see
 * `export_planner::resolve_tunnel_host`). Always surfaced, even when
 * `warnings` is empty — silently dropping this is what let a declined
 * dependency travel into a bundle unnoticed (2026-08-16 review finding).
 */
auto_pulled: Array<string>, };
