// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareImportSummary = { servers: number, tunnels: number, credentials: number, skipped: Array<string>, 
/**
 * True when the bundle carried credentials but they were held back
 * because no vault is unlocked on this machine (hosts and tunnels are
 * still imported). Always `false` for a `legacy_json` import — that
 * format never carries vault credentials.
 */
credentials_held_back: boolean, };
