// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShareExportSummary = { path: string, servers: number, tunnels: number, credentials: number, warnings: Array<string>, };
