// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoverBlock } from "./HoverBlock";
import type { SignatureParameter } from "./SignatureParameter";

export type SignatureInformation = { label: string, documentation: Array<HoverBlock>, parameters: Array<SignatureParameter>, activeParameter: number | null, };
