// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoverBlock } from "./HoverBlock";

export type SignatureParameter = { label: string, labelStartUtf16: number | null, labelEndUtf16: number | null, documentation: Array<HoverBlock>, };
