// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PalettePreview } from "./PalettePreview";
import type { ThemeSource } from "./ThemeSource";

/**
 * One entry returned by `list_terminal_themes`: either a theme that parsed
 * successfully (with its preview), or a broken theme file surfaced as a
 * `{ name, error }` pair so the picker can grey it out with the parse error
 * instead of hiding it. Untagged so the frontend sees exactly the two
 * documented shapes rather than an internal variant tag.
 */
export type ThemeListEntry = { name: string, source: ThemeSource, palettePreview: PalettePreview, shadowsBuiltin: boolean, } | { name: string, error: string, };
