// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThemeColors = { background: string, foreground: string, cursor_text: string, cursor_color: string, selection_text: string, selection_bg: string, black: string, red: string, green: string, yellow: string, blue: string, magenta: string, cyan: string, white: string, bright_black: string, bright_red: string, bright_green: string, bright_yellow: string, bright_blue: string, bright_magenta: string, bright_cyan: string, bright_white: string, dim_fg: string, panel_bg: string, tab_bar_bg: string, tab_border: string, input_bg: string, active_highlight: string, text_secondary: string, text_muted: string, 
/**
 * xterm.js `ITheme.extendedAnsi`: ANSI slots 16.. , element 0 == slot 16.
 * `None` means "this theme does not override that slot"; the frontend
 * turns those into `undefined`, which xterm leaves at its own default.
 * Empty when the theme carries no `indexed_colors` — the frontend then
 * omits the key entirely, so a theme without indexed colors produces the
 * exact xterm theme object it produced before this field existed.
 * See `crate::extended_ansi` for the hole-tolerance trace.
 */
extended_ansi: Array<string | null>, };
