// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitPhase } from "./CommitPhase";
import type { ConflictPolicy } from "./ConflictPolicy";
import type { ManagedArtifacts } from "./ManagedArtifacts";
import type { SourceFingerprint } from "./SourceFingerprint";
import type { TransferDirection } from "./TransferDirection";
import type { TransferEndpoint } from "./TransferEndpoint";
import type { TransferJobState } from "./TransferJobState";
import type { TransferOrigin } from "./TransferOrigin";
import type { TransferPriority } from "./TransferPriority";
import type { TransferProtocol } from "./TransferProtocol";

export type TransferJob = { id: string, protocol: TransferProtocol, direction: TransferDirection, origin: TransferOrigin, endpoint: TransferEndpoint, localPath: string, remotePath: string, fileName: string, batchId: string | null, priority: TransferPriority, queueOrder: number, hostKey: string, destinationKey: string, state: TransferJobState, sourceFingerprint: SourceFingerprint | null, durableCheckpoint: number, bytesTransferred: number, totalBytes: number, speedBytesPerSecond: number | null, etaSeconds: number | null, retryAttempt: number, maxAttempts: number, conflictPolicy: ConflictPolicy, artifacts: ManagedArtifacts | null, commitPhase: CommitPhase, createdAtMs: number, updatedAtMs: number, startedAtMs: number | null, finishedAtMs: number | null, };
