// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransferEndpoint = { "kind": "configured", serverEntryId: string, label: string, } | { "kind": "adHoc", host: string, port: number, user: string, proxyCommand: string | null, proxyJump: string | null, };
