// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransferQueueSummary = { queued: number, running: number, paused: number, attention: number, failed: number, active: number, history: number, queuePaused: boolean, };
