// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionReason } from "./AttentionReason";
import type { CompletionResult } from "./CompletionResult";

export type TransferJobState = { "kind": "queued" } | { "kind": "connecting" } | { "kind": "checking" } | { "kind": "running" } | { "kind": "paused" } | { "kind": "needsConnection", message: string, } | { "kind": "needsAttention", reason: AttentionReason, } | { "kind": "retryWaiting", attempt: number, nextRetryAtMs: number, } | { "kind": "completed", result: CompletionResult, } | { "kind": "failed", error: string, } | { "kind": "cancelled", cleanupError: string | null, };
