// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueSettings } from "./QueueSettings";
import type { TransferJob } from "./TransferJob";
import type { TransferQueueSummary } from "./TransferQueueSummary";

export type TransferQueueSnapshot = { revision: number, queuePaused: boolean, settings: QueueSettings, jobs: Array<TransferJob>, summary: TransferQueueSummary, recoveryError: string | null, };
