// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Consent for launching an adapter in a project.
 */
export type TrustDecision = "trusted" | "denied" | "revoked";
