// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrustDecision } from "./TrustDecision";

export type TrustedProject = { root: string, rootUri: string, adapterId: string | null, decision: TrustDecision, updatedAtMs: bigint, lastUsedAtMs: bigint | null, };
