// Run: node scripts/tests/test_vim_vendor_keymap.mjs
//
// The mapping seam, asserted against the SHIPPED artifact.
//
// test_editor_vim_glue.mjs already drives the real engine, but it imports it
// from crates/termlab_tauri/frontend/node_modules — the package a developer
// installed, not the bundle the app loads. The app loads
// vendor/codemirror/codemirror.js, generated by `npm run build:vendor` and
// git-ignored, and "Ctrl-O does nothing in the built app while every test is
// green" is exactly the failure that gap allows: an esbuild bundle that
// dropped, renamed or duplicated the vim engine would never show up in a test
// that never opens it.
//
// So this loads the bundle itself plus the real vim-mode.js, registers the
// navigation commands the app registers, and asks the engine what <C-o> and
// <C-i> resolve to. Nothing is stubbed but the app's own dependencies, which
// are the injection point vim-mode.js exists to have.
//
// The bundle is a browser IIFE, but it guards every DOM and navigator lookup
// (`typeof document < "u" ? document : {documentElement:{style:{}}}`), so a
// vm context with neither runs it — and a context with a HALF DOM does not.
// That is why this sandbox deliberately defines no `document`.
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const ROOT = path.resolve(import.meta.dirname, '../../crates/termlab_tauri/frontend');
const BUNDLE = path.join(ROOT, 'vendor/codemirror/codemirror.js');
const VIM_MODE = path.join(ROOT, 'app/features/editor/vim-mode.js');
const VIM_JUMP_TRACE = path.join(ROOT, 'app/features/editor/vim-jump-trace.js');

assert.ok(
  fs.existsSync(BUNDLE),
  `vendor bundle missing: run "npm run build:vendor" in ${ROOT} (it is generated and git-ignored)`,
);

// The smallest CodeMirror 5 adapter the engine's normal-mode path touches when
// it runs an action, mirroring test_editor_vim_glue.mjs's. `cm6` is where the
// adapter puts the EditorView, and it is the one field an action reads.
function vimAdapter(view) {
  let cursor = { line: 0, ch: 0 };
  return {
    cm6: view,
    state: {},
    curOp: null,
    getCursor: () => ({ line: cursor.line, ch: cursor.ch }),
    listSelections: () => [{ anchor: cursor, head: cursor }],
    setCursor(line, ch) {
      cursor = typeof line === 'object' && line !== null
        ? { line: line.line, ch: line.ch || 0 }
        : { line, ch: ch || 0 };
    },
    getOption: () => undefined,
    setOption() {},
    operation(fn) {
      this.curOp = this.curOp || {};
      try { return fn(); } finally { this.curOp = null; }
    },
    getLine: () => 'const value = 1;',
    lineCount: () => 40,
    firstLine: () => 0,
    lastLine: () => 39,
    getRange: () => '',
    getSelection: () => '',
    replaceRange() {},
    focus() {},
    scrollIntoView() {},
    on() {},
    off() {},
    setBookmark: (pos) => ({ find: () => pos, clear() {} }),
  };
}

// A fresh context per harness: the engine keeps process-wide state (its
// keymap and its jumplist live on the module), so two harnesses sharing one
// evaluation would not be independent.
function harness(options = {}) {
  const opts = options || {};
  const sandbox = {
    console, setTimeout, clearTimeout, Promise, self: {}, globalThis: {},
  };
  sandbox.window = sandbox;
  const toasts = [];
  sandbox.toast = {
    info: (title, body) => { toasts.push(['info', title, body]); },
    error: (title, body) => { toasts.push(['error', title, body]); },
    warn() {}, success() {},
  };
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(BUNDLE, 'utf8'), sandbox, { filename: BUNDLE });
  vm.runInContext(fs.readFileSync(VIM_JUMP_TRACE, 'utf8'), sandbox, { filename: VIM_JUMP_TRACE });
  vm.runInContext(fs.readFileSync(VIM_MODE, 'utf8'), sandbox, { filename: VIM_MODE });

  const calls = { back: 0, forward: 0, definitions: [] };
  const deps = {
    goToDefinition: (view) => { calls.definitions.push(view); return Promise.resolve('navigated'); },
    navigateBack: () => { calls.back += 1; return Promise.resolve('navigated'); },
    navigateForward: () => { calls.forward += 1; return Promise.resolve('navigated'); },
  };
  for (const omitted of opts.omit || []) delete deps[omitted];
  const registered = sandbox.termlabVimMode.registerNavigationCommands(deps);
  return { sandbox, calls, registered, toasts, Vim: sandbox.CM6.Vim };
}

const tick = () => new Promise((resolve) => { setTimeout(resolve, 0); });

const results = [];
function check(name, fn) { results.push({ name, fn }); }

check('the shipped bundle exports the vim engine the app resolves against', () => {
  const { sandbox } = harness();
  const CM = sandbox.CM6;
  assert.ok(CM, 'the bundle must define the CM6 global');
  assert.strictEqual(typeof CM.vim, 'function', 'CM6.vim() is the editor extension');
  assert.ok(CM.Vim, 'CM6.Vim is the command table');
  for (const name of ['defineAction', 'mapCommand', 'defineEx', 'findKey', 'getVimGlobalState_']) {
    assert.strictEqual(
      typeof CM.Vim[name], 'function',
      `CM6.Vim.${name} is gone from the bundle — vim-mode.js guards on it and would silently register nothing`,
    );
  }
});

check('Ctrl-O resolves to our back action against the shipped bundle', async () => {
  const h = harness();
  assert.strictEqual(h.registered, true, 'registerNavigationCommands accepted the bundle');
  const command = h.Vim.findKey(vimAdapter({ id: 'view' }), '<C-o>', 'test');
  assert.strictEqual(typeof command, 'function', 'the engine matched <C-o> to a command');
  command();
  await tick();
  assert.strictEqual(h.calls.back, 1, 'Ctrl-O walked the window history back');
  assert.strictEqual(h.calls.forward, 0);
});

check('Ctrl-I resolves to our forward action against the shipped bundle', async () => {
  const h = harness();
  const command = h.Vim.findKey(vimAdapter({ id: 'view' }), '<C-i>', 'test');
  assert.strictEqual(typeof command, 'function', 'the engine matched <C-i> to a command');
  command();
  await tick();
  assert.strictEqual(h.calls.forward, 1, 'Ctrl-I walked the window history forward');
  assert.strictEqual(h.calls.back, 0);
});

check("the bundle's own key translation still spells the two combinations <C-o>/<C-i>", () => {
  const { Vim } = harness();
  assert.strictEqual(Vim.vimKeyFromEvent({ key: 'o', ctrlKey: true }, {}), '<C-o>');
  assert.strictEqual(Vim.vimKeyFromEvent({ key: 'i', ctrlKey: true }, {}), '<C-i>');
  assert.strictEqual(
    Vim.vimKeyFromEvent({ key: 'Tab' }, {}), '<Tab>',
    'a Tab keydown is its own key, so insert-mode Tab is untouched by the <C-i> mapping',
  );
});

check('a window with no back/forward dependency leaves both keys unmapped', () => {
  const h = harness({ omit: ['navigateBack', 'navigateForward'] });
  assert.strictEqual(h.registered, true, 'gd is still registered');
  const adapter = vimAdapter({ id: 'view' });
  // Unmapped, the engine falls through to its own jumplist walk, which is a
  // command too — what must NOT happen is our action running.
  const back = h.Vim.findKey(adapter, '<C-o>', 'test');
  if (typeof back === 'function') back();
  assert.strictEqual(h.calls.back, 0, 'nothing of ours ran for a feature this window has not wired');
});

check('gd still resolves against the shipped bundle, the key that does work today', async () => {
  const h = harness();
  const view = { id: 'gd-view' };
  const adapter = vimAdapter(view);
  h.Vim.findKey(adapter, 'g', 'test');
  const command = h.Vim.findKey(adapter, 'd', 'test');
  assert.strictEqual(typeof command, 'function', 'the engine matched gd');
  command();
  await tick();
  assert.deepStrictEqual(h.calls.definitions, [view]);
});

let failed = 0;
for (const { name, fn } of results) {
  try {
    await fn();
    console.log(`  ok   ${name}`);
  } catch (error) {
    failed += 1;
    console.log(`  FAIL ${name}`);
    console.log(`       ${error && error.message}`);
  }
}
if (failed) {
  console.log(`vim vendor keymap: ${failed} of ${results.length} checks FAILED`);
  process.exitCode = 1;
} else {
  console.log(`vim vendor keymap: all ${results.length} checks passed`);
}
